#!/bin/sh

if [ "$1" == "" ]; then
    CMD="only"
else
    CMD=$1
fi

init_vga() {
    xrandr --newmode "1920x1080"  173.00  1920 2048 2248 2576  1080 1083 1088 1120 -hsync +vsync
    xrandr --addmode VGA1 1920x1080
    xrandr --output VGA1 --mode 1920x1080
}

case $CMD in
    "off")
        xrandr --output VGA1 --off --output LVDS1 --auto
        ;;
    "right")
        xrandr --output LVDS1 --auto --primary --output VGA1 --auto --right-of LVDS1
        init_vga
        ;;
    "only")
        xrandr --output LVDS1 --off
        init_vga
        ;;
esac

#xrandr --dpi 96
xrandr --dpi 125

